// 将数据组装起来
const testJson2 = {
  id: 0,
  children: [
    {
      id: 1479,
      parentId: 1360,
      name: "TT KOL 用户信息管理",
      path: "tt-kol-user",
      component: "kol/ttKolUser/index",
      icon: "",
      visible: true,
      keepAlive: true,
      children: null,
    },
    {
      id: 1485,
      parentId: 1360,
      name: "TT KOL 用户信息管理",
      path: "tt-kol-account",
      component: "kol/ttKolAccount/index",
      icon: "",
      visible: true,
      keepAlive: true,
      children: null,
    },
    {
      id: 1491,
      parentId: 1360,
      name: "TT KOL 内容管理",
      path: "tt-kol-content",
      component: "kol/ttKolContent/index",
      icon: "",
      visible: true,
      keepAlive: true,
      children: null,
    },
    {
      id: 1361,
      parentId: 1360,
      name: "TikTok视频剪辑",
      path: "/drama",
      component: null,
      icon: "#",
      visible: true,
      keepAlive: true,
      children: [
        {
          id: 1362,
          parentId: 1361,
          name: "需求库",
          path: "/drama/demand",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1363,
          parentId: 1361,
          name: "剧本库",
          path: "/drama/demand/play",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1365,
          parentId: 1361,
          name: "计划任务",
          path: "/drama/plan",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1366,
          parentId: 1361,
          name: "剪辑任务",
          path: "/drama/editing",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1523,
          parentId: 1361,
          name: "视频成品库",
          path: "/drama/video",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1367,
          parentId: 1361,
          name: "品牌分镜库",
          path: "/drama/brandShot",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1368,
          parentId: 1361,
          name: "印尼语翻译",
          path: "/drama/idlang",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1369,
          parentId: 1361,
          name: "我的审核",
          path: "/drama/audit",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1370,
          parentId: 1361,
          name: "剧本分类配置",
          path: "/drama/playTemplateType",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1371,
          parentId: 1361,
          name: "剧本模板草稿库",
          path: "/drama/playDraft",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1372,
          parentId: 1361,
          name: "剧本模板库",
          path: "/drama/playTemplate",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1472,
          parentId: 1361,
          name: "标签库",
          path: "/drama/label",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1473,
          parentId: 1361,
          name: "素材库",
          path: "/drama/material",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: [
            {
              id: 1460,
              parentId: 1473,
              name: "剪辑专用",
              path: "/drama/material/titokclip",
              component: null,
              icon: "#",
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 1461,
              parentId: 1473,
              name: "官方素材",
              path: "/drama/material/titokoffice",
              component: null,
              icon: "#",
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 1520,
              parentId: 1473,
              name: "Tiktok优质素材库（素材）",
              path: "/drama/material/titok",
              component: null,
              icon: "#",
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 1522,
              parentId: 1473,
              name: "Tiktok优质KOL配音",
              path: "/drama/material/titokvoice",
              component: null,
              icon: "#",
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 1497,
              parentId: 1473,
              name: "Tiktok优质KOL配音",
              path: "drama/material/goodtiktok",
              component: null,
              icon: "#",
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 1521,
              parentId: 1473,
              name: "IG优质KOL配音",
              path: "/drama/material/igvoice",
              component: null,
              icon: "#",
              visible: true,
              keepAlive: true,
              children: null,
            },
            {
              id: 1519,
              parentId: 1473,
              name: "IG优质素材库（素材）",
              path: "/drama/material/ig",
              component: null,
              icon: "#",
              visible: true,
              keepAlive: true,
              children: null,
            },
          ],
        },
      ],
    },
    {
      id: 1373,
      parentId: 1360,
      name: "供应链",
      path: "/supply",
      component: null,
      icon: "#",
      visible: true,
      keepAlive: true,
      children: [
        {
          id: 1374,
          parentId: 1373,
          name: "SKU库",
          path: "/supply/goods",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
      ],
    },
    {
      id: 1477,
      parentId: 1360,
      name: "TT KOL运营",
      path: "/TTkolOperate",
      component: null,
      icon: "#",
      visible: true,
      keepAlive: true,
      children: [
        {
          id: 1478,
          parentId: 1477,
          name: "预算管理",
          path: "/TTkolOperate/budget",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1503,
          parentId: 1477,
          name: "Deal进展",
          path: "/TTkolOperate/advance",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1508,
          parentId: 1477,
          name: "KOL管理",
          path: "/TTkolOperate/filter",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1504,
          parentId: 1477,
          name: "BD任务管理",
          path: "/TTkolOperate/bdtask",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1505,
          parentId: 1477,
          name: "任务处理",
          path: "/TTkolOperate/taskProcess",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1506,
          parentId: 1477,
          name: "KOL发布管理",
          path: "/TTkolOperate/release",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1507,
          parentId: 1477,
          name: "KOL内容库",
          path: "/TTkolOperate/content",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
      ],
    },
    {
      id: 1514,
      parentId: 1360,
      name: "KOL库",
      path: "/kol",
      component: null,
      icon: "#",
      visible: true,
      keepAlive: true,
      children: [
        {
          id: 1515,
          parentId: 1514,
          name: "IG KOL信息库",
          path: "/kol/iginfo",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1516,
          parentId: 1514,
          name: "Tiktok KOL信息库",
          path: "/kol/ttinfo",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1517,
          parentId: 1514,
          name: "IGKOL内容库",
          path: "/kol/igcontent",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
        {
          id: 1518,
          parentId: 1514,
          name: "Tiktok内容库",
          path: "/kol/ttcontent",
          component: null,
          icon: "#",
          visible: true,
          keepAlive: true,
          children: null,
        },
      ],
    },
  ],
};

let root2;

const generate = ({ path, component, name, icon }) => ({
  path,
  icon,
  component: lazyLoad(lazy(() => import(component))),
  meta: {
    title: name,
    auth: true,
  },
});

function register2(path, rootModule) {
  const ob = {
    path: rootModule.path,
    name: rootModule.name,
    component: rootModule.component,
    icon: rootModule.icon,
  };
  let newModule = {
    // _raw: rootModule,
    children: [],
    id: rootModule.id,
    ...generate(ob),
    // ...rootModule,
  };
  if (path.length === 0) {
    root2 = newModule;
  } else {
    let parent = path.slice(0, -1).reduce((root, current) => {
      return root.children[current];
    }, root2);
    const curIdx = path[path.length - 1];
    parent.children[curIdx] = newModule;
  }
  if (rootModule.children) {
    rootModule.children.forEach((child, idx) => {
      register2(path.concat(idx), child);
    });
  }
}

register2([], testJson2);

console.log("root2", JSON.stringify(root2, null, 2));
